name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Check out repo code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          python -m pip install -r quote_disp/requirements.txt
          python -m pip install -r quote_gen/requirements.txt
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov pytest-mock
      - name: Run quote_disp tests
        run: |
          cd quote_disp
          python -m pytest -v tests
      - name: Run quote_gen tests
        run: |
          cd quote_gen
          python -m pytest -v tests
      - name: Check coverage quote_disp
        run: |
          cd quote_disp
          pytest --cov=calculator --cov-report "xml:coverage.xml"  tests/
      - name: Write coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-xml-coverage-path: ./quote_disp/coverage.xml
      - name: Check coverage quote_gen
        run: |
          cd quote_gen
          pytest --cov=calculator --cov-report "xml:coverage.xml"  tests/
      - name: Write coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-xml-coverage-path: ./quote_gen/coverage.xml